<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ReferenceAtomData>true</ReferenceAtomData>
    <ReferenceAtomDataEf>true</ReferenceAtomDataEf>
    <ReferenceAtomInfrastructure>true</ReferenceAtomInfrastructure>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PriceChecker.Core\PriceChecker.Core.csproj" />
    <ProjectReference Include="..\PriceChecker.Dto\PriceChecker.Dto.csproj" />
  </ItemGroup>

</Project>
