// <auto-generated />
using System;
using Genius.PriceChecker.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Genius.PriceChecker.Db.Migrations
{
    [DbContext(typeof(PriceCheckerDbContext))]
    partial class PriceCheckerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Genius.PriceChecker.Db.Models.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("DateCreated")
                        .HasColumnType("INTEGER");

                    b.Property<char>("DecimalDelimiter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Handler")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PricePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Genius.PriceChecker.Db.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<long>("DateCreated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Genius.PriceChecker.Db.Models.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("DateCreated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FoundDate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductSourceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductSourceId");

                    b.ToTable("ProductPrices");
                });

            modelBuilder.Entity("Genius.PriceChecker.Db.Models.ProductSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentArgument")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DateCreated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSources");
                });

            modelBuilder.Entity("Genius.PriceChecker.Db.Models.ProductPrice", b =>
                {
                    b.HasOne("Genius.PriceChecker.Db.Models.ProductSource", "ProductSource")
                        .WithMany("Prices")
                        .HasForeignKey("ProductSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSource");
                });

            modelBuilder.Entity("Genius.PriceChecker.Db.Models.ProductSource", b =>
                {
                    b.HasOne("Genius.PriceChecker.Db.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Genius.PriceChecker.Db.Models.Product", "Product")
                        .WithMany("Sources")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Genius.PriceChecker.Db.Models.Product", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Genius.PriceChecker.Db.Models.ProductSource", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
