//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.0.0 (NJsonSchema v11.6.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { ApiClientBase } from "@hwndmaster/atom-api-core";
import { ApiResponse } from "@hwndmaster/atom-api-core";
import { AgentRef, ProductRef, ProductSourceRef, ProductPriceRef } from "@/models/types";import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export class AgentsClient extends ApiClientBase {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "http://localhost:5080/";

    }

    static operations = {

        handlers: "api/v1/Agents/handlers",
        agentsGET: "api/v1/Agents/{id}",
        agentsDELETE: "api/v1/Agents/{id}",
        agentsAll: "api/v1/Agents",
        agentsPOST: "api/v1/Agents",
        agentsPUT: "api/v1/Agents",
        byIds: "api/v1/Agents/by-ids",
    }

    static operationParams = {

        handlers: {} as {
        },

        agentsGET: {} as {
            id: AgentRef;
        },

        agentsDELETE: {} as {
            id: AgentRef;
        },

        agentsAll: {} as {
        },

        agentsPOST: {} as {
            body: Partial<CreateAgentRequest>;
        },

        agentsPUT: {} as {
            body: Partial<UpdateAgentRequest>;
        },

        byIds: {} as {
            body: Partial<AgentRef[]>;
        },
    }

    /**
     * @return OK
     */
    handlers( cancelToken?: CancelToken): Promise<ApiResponse<string[]>> {
        let url_ = this.baseUrl + "/api/v1/Agents/handlers";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processHandlers(_response);
        });
    }

    protected processHandlers(response: AxiosResponse): Promise<ApiResponse<string[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<string[]>>(new ApiResponse<string[]>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<string[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    agentsGET(id: AgentRef, cancelToken?: CancelToken): Promise<ApiResponse<AgentDto>> {
        let url_ = this.baseUrl + "/api/v1/Agents/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAgentsGET(_response);
        });
    }

    protected processAgentsGET(response: AxiosResponse): Promise<ApiResponse<AgentDto>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<AgentDto>>(new ApiResponse<AgentDto>(status, _headers, result200));

        } else if (status === 404) {
            const _responseText = response.data;
            return throwException("Not Found", status, _responseText, _headers);

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<AgentDto>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    agentsDELETE(id: AgentRef, cancelToken?: CancelToken): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/api/v1/Agents/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAgentsDELETE(_response);
        });
    }

    protected processAgentsDELETE(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    agentsAll( cancelToken?: CancelToken): Promise<ApiResponse<AgentDto[]>> {
        let url_ = this.baseUrl + "/api/v1/Agents";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAgentsAll(_response);
        });
    }

    protected processAgentsAll(response: AxiosResponse): Promise<ApiResponse<AgentDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<AgentDto[]>>(new ApiResponse<AgentDto[]>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<AgentDto[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    agentsPOST(body: CreateAgentRequest, cancelToken?: CancelToken): Promise<ApiResponse<CreatedEntityDtoOfGuidAndAgentRef>> {
        let url_ = this.baseUrl + "/api/v1/Agents";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAgentsPOST(_response);
        });
    }

    protected processAgentsPOST(response: AxiosResponse): Promise<ApiResponse<CreatedEntityDtoOfGuidAndAgentRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<CreatedEntityDtoOfGuidAndAgentRef>>(new ApiResponse<CreatedEntityDtoOfGuidAndAgentRef>(status, _headers, result200));

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = typeof(resultData400) === "object" ? resultData400 : JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<CreatedEntityDtoOfGuidAndAgentRef>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    agentsPUT(body: UpdateAgentRequest, cancelToken?: CancelToken): Promise<ApiResponse<UpdatedEntityDtoOfGuidAndAgentRef>> {
        let url_ = this.baseUrl + "/api/v1/Agents";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAgentsPUT(_response);
        });
    }

    protected processAgentsPUT(response: AxiosResponse): Promise<ApiResponse<UpdatedEntityDtoOfGuidAndAgentRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<UpdatedEntityDtoOfGuidAndAgentRef>>(new ApiResponse<UpdatedEntityDtoOfGuidAndAgentRef>(status, _headers, result200));

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = typeof(resultData400) === "object" ? resultData400 : JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<UpdatedEntityDtoOfGuidAndAgentRef>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    byIds(body: AgentRef[], cancelToken?: CancelToken): Promise<ApiResponse<AgentDto[]>> {
        let url_ = this.baseUrl + "/api/v1/Agents/by-ids";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAgents_byIds(_response);
        });
    }

    protected processAgents_byIds(response: AxiosResponse): Promise<ApiResponse<AgentDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<AgentDto[]>>(new ApiResponse<AgentDto[]>(status, _headers, result200));

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = typeof(resultData400) === "object" ? resultData400 : JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<AgentDto[]>>(new ApiResponse(status, _headers, null as any));
    }
}

export class ProductsClient extends ApiClientBase {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "http://localhost:5080/";

    }

    static operations = {

        overview: "api/v1/Products/overview",
        prices: "api/v1/Products/{productId}/prices",
        dropPrices: "api/v1/Products/{productId}/drop-prices",
        productsGET: "api/v1/Products/{id}",
        productsDELETE: "api/v1/Products/{id}",
        productsAll: "api/v1/Products",
        productsPOST: "api/v1/Products",
        productsPUT: "api/v1/Products",
        byIds: "api/v1/Products/by-ids",
    }

    static operationParams = {

        overview: {} as {
        },

        prices: {} as {
            productId: string;
        },

        dropPrices: {} as {
            productId: string;
        },

        productsGET: {} as {
            id: ProductRef;
        },

        productsDELETE: {} as {
            id: ProductRef;
        },

        productsAll: {} as {
        },

        productsPOST: {} as {
            body: Partial<CreateProductRequest>;
        },

        productsPUT: {} as {
            body: Partial<UpdateProductRequest>;
        },

        byIds: {} as {
            body: Partial<ProductRef[]>;
        },
    }

    /**
     * @return OK
     */
    overview( cancelToken?: CancelToken): Promise<ApiResponse<ProductOverviewDto[]>> {
        let url_ = this.baseUrl + "/api/v1/Products/overview";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processOverview(_response);
        });
    }

    protected processOverview(response: AxiosResponse): Promise<ApiResponse<ProductOverviewDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<ProductOverviewDto[]>>(new ApiResponse<ProductOverviewDto[]>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<ProductOverviewDto[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    prices(productId: string, cancelToken?: CancelToken): Promise<ApiResponse<ProductPriceDto[]>> {
        let url_ = this.baseUrl + "/api/v1/Products/{productId}/prices";
        if (productId === undefined || productId === null)
            throw new Error("The parameter 'productId' must be defined.");
        url_ = url_.replace(/{productId}/gi, encodeURIComponent("" + productId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPrices(_response);
        });
    }

    protected processPrices(response: AxiosResponse): Promise<ApiResponse<ProductPriceDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<ProductPriceDto[]>>(new ApiResponse<ProductPriceDto[]>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<ProductPriceDto[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    dropPrices(productId: string, cancelToken?: CancelToken): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/api/v1/Products/{productId}/drop-prices";
        if (productId === undefined || productId === null)
            throw new Error("The parameter 'productId' must be defined.");
        url_ = url_.replace(/{productId}/gi, encodeURIComponent("" + productId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDropPrices(_response);
        });
    }

    protected processDropPrices(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    productsGET(id: ProductRef, cancelToken?: CancelToken): Promise<ApiResponse<ProductDto>> {
        let url_ = this.baseUrl + "/api/v1/Products/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProductsGET(_response);
        });
    }

    protected processProductsGET(response: AxiosResponse): Promise<ApiResponse<ProductDto>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<ProductDto>>(new ApiResponse<ProductDto>(status, _headers, result200));

        } else if (status === 404) {
            const _responseText = response.data;
            return throwException("Not Found", status, _responseText, _headers);

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<ProductDto>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    productsDELETE(id: ProductRef, cancelToken?: CancelToken): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/api/v1/Products/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace(/{id}/gi, encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProductsDELETE(_response);
        });
    }

    protected processProductsDELETE(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    productsAll( cancelToken?: CancelToken): Promise<ApiResponse<ProductDto[]>> {
        let url_ = this.baseUrl + "/api/v1/Products";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProductsAll(_response);
        });
    }

    protected processProductsAll(response: AxiosResponse): Promise<ApiResponse<ProductDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<ProductDto[]>>(new ApiResponse<ProductDto[]>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<ProductDto[]>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    productsPOST(body: CreateProductRequest, cancelToken?: CancelToken): Promise<ApiResponse<CreatedEntityDtoOfGuidAndProductRef>> {
        let url_ = this.baseUrl + "/api/v1/Products";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProductsPOST(_response);
        });
    }

    protected processProductsPOST(response: AxiosResponse): Promise<ApiResponse<CreatedEntityDtoOfGuidAndProductRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<CreatedEntityDtoOfGuidAndProductRef>>(new ApiResponse<CreatedEntityDtoOfGuidAndProductRef>(status, _headers, result200));

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = typeof(resultData400) === "object" ? resultData400 : JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<CreatedEntityDtoOfGuidAndProductRef>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    productsPUT(body: UpdateProductRequest, cancelToken?: CancelToken): Promise<ApiResponse<UpdatedEntityDtoOfGuidAndProductRef>> {
        let url_ = this.baseUrl + "/api/v1/Products";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProductsPUT(_response);
        });
    }

    protected processProductsPUT(response: AxiosResponse): Promise<ApiResponse<UpdatedEntityDtoOfGuidAndProductRef>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<UpdatedEntityDtoOfGuidAndProductRef>>(new ApiResponse<UpdatedEntityDtoOfGuidAndProductRef>(status, _headers, result200));

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = typeof(resultData400) === "object" ? resultData400 : JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<UpdatedEntityDtoOfGuidAndProductRef>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    byIds(body: ProductRef[], cancelToken?: CancelToken): Promise<ApiResponse<ProductDto[]>> {
        let url_ = this.baseUrl + "/api/v1/Products/by-ids";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProducts_byIds(_response);
        });
    }

    protected processProducts_byIds(response: AxiosResponse): Promise<ApiResponse<ProductDto[]>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<ProductDto[]>>(new ApiResponse<ProductDto[]>(status, _headers, result200));

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = typeof(resultData400) === "object" ? resultData400 : JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<ProductDto[]>>(new ApiResponse(status, _headers, null as any));
    }
}

export class ScansClient extends ApiClientBase {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        super();

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "http://localhost:5080/";

    }

    static operations = {

        all: "api/v1/Scans/all",
        product: "api/v1/Scans/product/{productId}",
        progress: "api/v1/Scans/progress",
    }

    static operationParams = {

        all: {} as {
        },

        product: {} as {
            productId: string;
        },

        progress: {} as {
        },
    }

    /**
     * @return OK
     */
    all( cancelToken?: CancelToken): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/api/v1/Scans/all";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAll(_response);
        });
    }

    protected processAll(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    product(productId: string, cancelToken?: CancelToken): Promise<ApiResponse<void>> {
        let url_ = this.baseUrl + "/api/v1/Scans/product/{productId}";
        if (productId === undefined || productId === null)
            throw new Error("The parameter 'productId' must be defined.");
        url_ = url_.replace(/{productId}/gi, encodeURIComponent("" + productId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProduct(_response);
        });
    }

    protected processProduct(response: AxiosResponse): Promise<ApiResponse<void>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<ApiResponse<void>>(new ApiResponse<void>(status, _headers, null as any));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<void>>(new ApiResponse(status, _headers, null as any));
    }

    /**
     * @return OK
     */
    progress( cancelToken?: CancelToken): Promise<ApiResponse<ScanProgressDto>> {
        let url_ = this.baseUrl + "/api/v1/Scans/progress";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.instance.request(transformedOptions_);
        }).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processProgress(_response);
        });
    }

    protected processProgress(response: AxiosResponse): Promise<ApiResponse<ScanProgressDto>> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = typeof(resultData200) === "object" ? resultData200 : JSON.parse(resultData200);
            return Promise.resolve<ApiResponse<ScanProgressDto>>(new ApiResponse<ScanProgressDto>(status, _headers, result200));

        } else if (status === 404) {
            return throwException("NotFound: " + response.config.url, status, response.data, _headers, null);
        }
        else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<ScanProgressDto>>(new ApiResponse(status, _headers, null as any));
    }
}

export interface AgentDto {
    id: AgentRef;
    key: string;
    url: string;
    pricePattern: string;
    handler: string;
    decimalDelimiter: string;
    dateCreated: number;
    lastModified: number;
}

export interface CreateAgentRequest {
    key: string;
    url: string;
    pricePattern: string;
    handler: string;
    decimalDelimiter: string;
}

export interface CreatedEntityDtoOfGuidAndAgentRef {
    entityId: AgentRef;
    lastModified: number;
}

export interface CreatedEntityDtoOfGuidAndProductRef {
    entityId: ProductRef;
    lastModified: number;
}

export interface CreateProductRequest {
    name: string;
    category: string | undefined;
    description: string | undefined;
    sources: CreateProductSourceRequest[];
}

export interface CreateProductSourceRequest {
    agentId: AgentRef;
    agentArgument: string;
}

export interface HttpValidationProblemDetails {
    type: string | undefined;
    title: string | undefined;
    status: number | undefined;
    detail: string | undefined;
    instance: string | undefined;
    errors: { [key: string]: string[]; };
}

export interface ProductDto {
    id: ProductRef;
    name: string;
    category: string | undefined;
    description: string | undefined;
    sources: ProductSourceDto[];
    dateCreated: number;
    lastModified: number;
}

export interface ProductOverviewDto {
    id: ProductRef;
    name: string;
    category: string | undefined;
    description: string | undefined;
    status: number;
    lowestPrice: number | undefined;
    lowestFoundDate: number | undefined;
    recentPrice: number | undefined;
    lastScannedDate: number | undefined;
    lastModified: number;
}

export interface ProductPriceDto {
    id: ProductPriceRef;
    productSourceId: ProductSourceRef;
    status: number;
    price: number | undefined;
    foundDate: number;
}

export interface ProductSourceDto {
    id: ProductSourceRef;
    agentId: AgentRef;
    agentArgument: string;
}

export interface ScanProgressDto {
    finished: number;
    total: number;
    hasErrors: boolean;
    hasNewLowestPrice: boolean;
    isFinished: boolean;
}

export interface UpdateAgentRequest {
    id: AgentRef;
    lastModified: number;
    key: string;
    url: string;
    pricePattern: string;
    handler: string;
    decimalDelimiter: string;
}

export interface UpdatedEntityDtoOfGuidAndAgentRef {
    entityId: AgentRef;
    lastModified: number;
}

export interface UpdatedEntityDtoOfGuidAndProductRef {
    entityId: ProductRef;
    lastModified: number;
}

export interface UpdateProductRequest {
    id: ProductRef;
    lastModified: number;
    name: string;
    category: string | undefined;
    description: string | undefined;
    sources: UpdateProductSourceRequest[];
}

export interface UpdateProductSourceRequest {
    id: ProductSourceRef | undefined;
    agentId: AgentRef;
    agentArgument: string;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}