<Project>
  <PropertyGroup>
    <Version>1.0.2</Version>
    <Product>Price Checker</Product>
    <Authors>Dima Kravtsov</Authors>
    <Description>A simple price checker</Description>
    <RepositoryUrl>https://github.com/hwndmaster/price-checker</RepositoryUrl>

    <NoWarn>NU1604</NoWarn>

    <RootNamespace>Genius.$(MSBuildProjectName)</RootNamespace>
    <AssemblyName>$(RootNamespace)</AssemblyName>

    <AtomPackageVersion>0.0.43</AtomPackageVersion>
    <AtomBuildDirectory>$(USERPROFILE)\.nuget\packages\genius.atom.build\$(AtomPackageVersion)\build</AtomBuildDirectory>
  </PropertyGroup>

  <Import Project="$(AtomBuildDirectory)\Genius.Atom.Build.props" />
  <Import Project="$(AtomBuildDirectory)\AtomReferences.targets" />

</Project>
