<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ReferenceAtomData>true</ReferenceAtomData>
    <ReferenceAtomDataEf>true</ReferenceAtomDataEf>
    <ReferenceAtomInfrastructure>true</ReferenceAtomInfrastructure>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PriceChecker.Db\PriceChecker.Db.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Used in Atom.Data.Ef.TestingUtil, but here to ensure the package availability -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

</Project>
