<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ReferenceAtomData>true</ReferenceAtomData>
    <ReferenceAtomDataEf>true</ReferenceAtomDataEf>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PriceChecker.Core\PriceChecker.Core.csproj" />
  </ItemGroup>

</Project>
