name: WPF CD

jobs:
  release:
    name: Release
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Create release
      shell: bash
      run: |
        tag=$(git describe --tags --abbrev=0)
        release_name="PriceChecker-$tag-${{ matrix.target }}"
        dotnet publish PriceChecker.UI/PriceChecker.UI.csproj --runtime "win-x64" -c Release -o "$release_name"
        7z a -tzip "${release_name}.zip" "./${release_name}/*"
        rm -r "$release_name"
    - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "PriceChecker*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
