name: CD

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: read

jobs:
  release:
    name: Release
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Authenticate GitHub Packages for NuGet
        run: dotnet nuget update source github --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --configfile nuget.config

      - name: Restore .NET tools
        run: dotnet tool restore --configfile nuget.config

      - name: Restore .NET dependencies
        run: dotnet restore PriceChecker.UI/PriceChecker.UI.csproj --configfile nuget.config --runtime win-x64

      - name: Build
        run: dotnet build PriceChecker.UI/PriceChecker.UI.csproj --runtime win-x64 --configuration Release --no-restore

      - name: Create release (clean)
        shell: bash
        run: |
          release_name="PriceChecker-${{ github.event.release.tag_name }}-x64"
          dotnet publish PriceChecker.UI/PriceChecker.UI.csproj --runtime win-x64 -c Release -o "${release_name}" --self-contained false --no-restore --no-build /p:DebugType=None /p:DebugSymbols=false
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
          rm -r "$release_name"

      - name: Create release (self contained)
        shell: bash
        run: |
          release_name_sc="PriceChecker-${{ github.event.release.tag_name }}-bundle-x64"
          dotnet publish PriceChecker.UI/PriceChecker.UI.csproj --runtime win-x64 -c Release -o "${release_name_sc}" --self-contained true --no-restore --no-build /p:DebugType=None /p:DebugSymbols=false
          7z a -tzip "${release_name_sc}.zip" "./${release_name_sc}/*"
          rm -r "$release_name_sc"

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            PriceChecker-${{ github.event.release.tag_name }}-x64.zip
            PriceChecker-${{ github.event.release.tag_name }}-bundle-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
