name: WPF CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/hwndmaster/index.json -n github -u hwndmaster -p ${{ secrets.PRIVATE_PKG_TOKEN }} --store-password-in-clear-text
        dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Cleanup
      if: always()
      continue-on-error: true
      run: |
        dotnet nuget remove source github